version: '3.4'

services:
  finance-db:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    networks:
      - finance-network

  finance-api:
    image: finance-api
    build:
      context: .
      dockerfile: FinanceSystem.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=finance-db;Database=SistemaFinanceiro;User Id=sa;Password=TesteUneC0nt@Alain;
    ports:
      - "5000:7042"
    networks:
      - finance-network

  finance-web:
    image: finance-web
    build:
      context: .
      dockerfile: FinanceSystem.WebApp/Dockerfile
    ports:
      - "5001:7057"
    networks:
      - finance-network

networks:
  finance-network:
